#!/usr/bin/env node
const process = require("process");
const fs = require("fs");
const http = require("http");

process.stdout.write('Starting server ... ');

const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Cloudbleed</title>
  <style>
    body {
      margin: 0;
      display: flex;
      flex-wrap: wrap;
    }

    a {
      width: 1px;
      height: 1px;
    }

    :link { background-color: #ffffcd; }
    :visited { background-color: black; }
  </style>
</head>
<body>${fs
  .readFileSync("sorted_unique_cf.txt", "utf8")
  .split("\n")
  .map((host) => `<a href="https://${host}"></a>`)
  .join('')}</body>
</html>
`;

http
  .createServer((req, res) => {
    res.writeHead(200, { "Content-Type": "text/html" });
    res.end(html, "utf-8");
    console.log('request: ', req.url);
  })
  .listen(4567);

console.log(`done!

See http://localhost:4567
`);
